# Model details
model:
  name: "pix2struct"  # Change to "docowl" for DocOWL model
  config:
    model_name: "weights/pix2struct-base_4096_7"
    processor_name: "ybelkada/pix2struct-base"
    device: 0
    # Add other model-specific configurations here
  # name: "docowl"  # Change to "docowl" for DocOWL model
  # config:
  #   model_name: "weights/pix2struct-base_4096_7"
  #   processor_name: "ybelkada/pix2struct-base"
  #   device: 0
  #   # Add other model-specific configurations here

# Directories
image_directory: "/data/circulars/DATA/Batches-Split_Images"
json_directory: "/data/circulars/CircularsGPT_M/data/"

# Model Configuration:
validation_size: 0.1
max_patches: 4096
random_state: 42

# Training Configuration:
device: "cuda:1"
learning_rate: 0.00001
epochs: 50
batch_size: 1

# Path for saving weight files
weight_path: "/data/circulars/CircularsGPT_M/weights"

# Path for logging
logger_path: "/data/circulars/CircularsGPT_M/logging/circulars_base_2048.txt"